'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=C:\BTMS\Release\GovEngine.sdf")>  _
        Public Property LocalConnectionString() As String
            Get
                Return CType(Me("LocalConnectionString"),String)
            End Get
            Set
                Me("LocalConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\BTMS\Release\GovEngine.sdf")>  _
        Public Property DatabasePath() As String
            Get
                Return CType(Me("DatabasePath"),String)
            End Get
            Set
                Me("DatabasePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DEPARTMENT OF INTERIOR AND LOCAL GOVERNMENT"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"REGIONAL OFFICE I")>  _
        Public Property CompanyName() As String
            Get
                Return CType(Me("CompanyName"),String)
            End Get
            Set
                Me("CompanyName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Region() As String
            Get
                Return CType(Me("Region"),String)
            End Get
            Set
                Me("Region") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CompanyLogo() As String
            Get
                Return CType(Me("CompanyLogo"),String)
            End Get
            Set
                Me("CompanyLogo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Absent")>  _
        Public Property dtr_remarks_for_absent() As String
            Get
                Return CType(Me("dtr_remarks_for_absent"),String)
            End Get
            Set
                Me("dtr_remarks_for_absent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("A")>  _
        Public Property sra_remarks_for_absent() As String
            Get
                Return CType(Me("sra_remarks_for_absent"),String)
            End Get
            Set
                Me("sra_remarks_for_absent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Off")>  _
        Public Property dtr_remarks_for_dayoff() As String
            Get
                Return CType(Me("dtr_remarks_for_dayoff"),String)
            End Get
            Set
                Me("dtr_remarks_for_dayoff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Off")>  _
        Public Property sra_remarks_for_dayoff() As String
            Get
                Return CType(Me("sra_remarks_for_dayoff"),String)
            End Get
            Set
                Me("sra_remarks_for_dayoff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\BTMS\Backup\")>  _
        Public Property DbBackup_initialpath() As String
            Get
                Return CType(Me("DbBackup_initialpath"),String)
            End Get
            Set
                Me("DbBackup_initialpath") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=C:\BTMS\Release\GovEngine.sdf")>  _
        Public ReadOnly Property GovEngineConnectionString_ix() As String
            Get
                Return CType(Me("GovEngineConnectionString_ix"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\GovEngine.sdf")>  _
        Public Property GovEngineConnectionString_ixold() As String
            Get
                Return CType(Me("GovEngineConnectionString_ixold"),String)
            End Get
            Set
                Me("GovEngineConnectionString_ixold") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Author: Brylle Lloren")>  _
        Public Property Engineeredby() As String
            Get
                Return CType(Me("Engineeredby"),String)
            End Get
            Set
                Me("Engineeredby") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("07:30")>  _
        Public Property dilg_flex_onduty_rules() As String
            Get
                Return CType(Me("dilg_flex_onduty_rules"),String)
            End Get
            Set
                Me("dilg_flex_onduty_rules") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16:30")>  _
        Public Property dilg_flex_offduty_rules() As String
            Get
                Return CType(Me("dilg_flex_offduty_rules"),String)
            End Get
            Set
                Me("dilg_flex_offduty_rules") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property dilg_rules_enabled() As String
            Get
                Return CType(Me("dilg_rules_enabled"),String)
            End Get
            Set
                Me("dilg_rules_enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property zk_con_string() As String
            Get
                Return CType(Me("zk_con_string"),String)
            End Get
            Set
                Me("zk_con_string") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property zk_mdb_path() As String
            Get
                Return CType(Me("zk_mdb_path"),String)
            End Get
            Set
                Me("zk_mdb_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property att2000_sync() As Boolean
            Get
                Return CType(Me("att2000_sync"),Boolean)
            End Get
            Set
                Me("att2000_sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DPWH_Rules() As Boolean
            Get
                Return CType(Me("DPWH_Rules"),Boolean)
            End Get
            Set
                Me("DPWH_Rules") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MOD_FORGET_CIN_COUT() As Boolean
            Get
                Return CType(Me("MOD_FORGET_CIN_COUT"),Boolean)
            End Get
            Set
                Me("MOD_FORGET_CIN_COUT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RTM() As Boolean
            Get
                Return CType(Me("RTM"),Boolean)
            End Get
            Set
                Me("RTM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DTR_A() As Boolean
            Get
                Return CType(Me("DTR_A"),Boolean)
            End Get
            Set
                Me("DTR_A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DTR_B() As Boolean
            Get
                Return CType(Me("DTR_B"),Boolean)
            End Get
            Set
                Me("DTR_B") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DTR_C() As Boolean
            Get
                Return CType(Me("DTR_C"),Boolean)
            End Get
            Set
                Me("DTR_C") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DTR_D() As Boolean
            Get
                Return CType(Me("DTR_D"),Boolean)
            End Get
            Set
                Me("DTR_D") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DTR_E() As Boolean
            Get
                Return CType(Me("DTR_E"),Boolean)
            End Get
            Set
                Me("DTR_E") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DTR_F() As Boolean
            Get
                Return CType(Me("DTR_F"),Boolean)
            End Get
            Set
                Me("DTR_F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rsrv_0() As String
            Get
                Return CType(Me("rsrv_0"),String)
            End Get
            Set
                Me("rsrv_0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rsrv_1() As String
            Get
                Return CType(Me("rsrv_1"),String)
            End Get
            Set
                Me("rsrv_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rsrv_2() As String
            Get
                Return CType(Me("rsrv_2"),String)
            End Get
            Set
                Me("rsrv_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rsrv_3() As String
            Get
                Return CType(Me("rsrv_3"),String)
            End Get
            Set
                Me("rsrv_3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rsrv_4() As String
            Get
                Return CType(Me("rsrv_4"),String)
            End Get
            Set
                Me("rsrv_4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rsrv_5() As String
            Get
                Return CType(Me("rsrv_5"),String)
            End Get
            Set
                Me("rsrv_5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rsrv_6() As String
            Get
                Return CType(Me("rsrv_6"),String)
            End Get
            Set
                Me("rsrv_6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rsrv_7() As String
            Get
                Return CType(Me("rsrv_7"),String)
            End Get
            Set
                Me("rsrv_7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rsrv_8() As String
            Get
                Return CType(Me("rsrv_8"),String)
            End Get
            Set
                Me("rsrv_8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b1001() As String
            Get
                Return CType(Me("dilg_0b1001"),String)
            End Get
            Set
                Me("dilg_0b1001") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b1000() As String
            Get
                Return CType(Me("dilg_0b1000"),String)
            End Get
            Set
                Me("dilg_0b1000") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b0001() As String
            Get
                Return CType(Me("dilg_0b0001"),String)
            End Get
            Set
                Me("dilg_0b0001") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b0011() As String
            Get
                Return CType(Me("dilg_0b0011"),String)
            End Get
            Set
                Me("dilg_0b0011") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b1100() As String
            Get
                Return CType(Me("dilg_0b1100"),String)
            End Get
            Set
                Me("dilg_0b1100") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b1101() As String
            Get
                Return CType(Me("dilg_0b1101"),String)
            End Get
            Set
                Me("dilg_0b1101") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b0111() As String
            Get
                Return CType(Me("dilg_0b0111"),String)
            End Get
            Set
                Me("dilg_0b0111") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b0100() As String
            Get
                Return CType(Me("dilg_0b0100"),String)
            End Get
            Set
                Me("dilg_0b0100") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b1011() As String
            Get
                Return CType(Me("dilg_0b1011"),String)
            End Get
            Set
                Me("dilg_0b1011") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b0110() As String
            Get
                Return CType(Me("dilg_0b0110"),String)
            End Get
            Set
                Me("dilg_0b0110") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b0010() As String
            Get
                Return CType(Me("dilg_0b0010"),String)
            End Get
            Set
                Me("dilg_0b0010") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dilg_0b1110() As String
            Get
                Return CType(Me("dilg_0b1110"),String)
            End Get
            Set
                Me("dilg_0b1110") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.BTMS.My.MySettings
            Get
                Return Global.BTMS.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
